# Generated by Django 5.2.4 on 2025-07-23 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="like",
            name="updated_at",
        ),
    ]
